name: Release
run-name: Release ${{ github.ref }}

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Setup node@18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - name: Install Dependency
        run: npm ci
      - name: Lint & Build
        run: |
          npm run lint
          npm run build
          pwd
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "custom_components/**/*,hacs.json"
          body: |
            Many different improvements. 
            And to be honest, I didn't figure out how 
            to add text from github workflow here.
          draft: false
          prerelease: false

